services:
  - type: web
    name: tbl-grocery-scanner
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn elegant_app:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: PORT
        value: "10000"
